### ISSUE TITLE
Can't create VM at step 2

### ISSUE THREAD

**Issue by gearsmotion789** [Azure-Samples/IoTEdgeAndMlSample#45]
I've been trying to follow the instructions at https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-machine-learning-edge-02-prepare-environment to setup a VM via the command `.\Create-AzureDevVm.ps1`. However, I got an error. How can I get it to work?

```
New-AzureRmResourceGroupDeployment : 3:54:50 PM - Error: Code=InvalidTemplateDeployment; Message=The template
deployment 'IotEdgeMlDemoVm-YzZCl' is not valid according to the validation procedure. The tracking id is
'b26486f9-46ff-4d10-8dec-20872a3176c7'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage
details.
At C:\Users\HomeHPi7\Desktop\IoTEdgeAndMlSample-master\DevVM\Create-AzureDevVm.ps1:147 char:19
+ ... eployment = New-AzureRmResourceGroupDeployment -Name $deploymentName  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDep
   loymentCmdlet
```

**Comment by kgremban** [comment]
@gearsmotion789 Can you run the following command with the tracking ID from your error to see if that provides more helpful details?

Get-AzureRMLog -CorrelationId xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -DetailedOutput

**Comment by drwill-ms** [comment]
@gearsmotion789 I ran through the script today and got failures twice due to VM size selection when I chose West US 2 and West US as my regions (for my subscription), but it succeeded when I chose East US. My error specifically indicated that it was a VM size problem, but yours above does not.

I mention this to show that I was able to get the script to work, but as our errors didn't match we'd like to know more about the details of your failure. The command @kgremban asked you to run will help us figure that out. However, you might try changing to a different region (as I did) to see if that unblocks you.

**Comment by JotunheimOnTb** [comment]
i got the same error of @gearsmotion789. I'm running PowerShell on MacOS.
@kgremban here is my log:

Authorization        : 
                       Scope     : /subscriptions/edaac790-1c73-4ad6-99fa-7eb59a597b4b/resourcegroups/Gruppo_ML/providers/Microsoft.Resources/deployments/IotEdgeMlDemoVm-oxwIZ
                       Action    : Microsoft.Resources/deployments/validate/action
                       Role      : 
                       Condition : 
Claims               : 
                       aud            : https://management.core.windows.net/
                       iss            : https://sts.windows.net/7ca361c3-9161-4ae8-b172-5dfcbd2c5539/
                       iat            : 1570439002
                       nbf            : 1570439002
                       exp            : 1570442902
                       http://schemas.microsoft.com/claims/authnclassreference: 1
                       aio            : 42VgYJApV/dRkHojeo37qmLQg1Llvcfmfgx/9UTOQ91zc7/3aiYA
                       http://schemas.microsoft.com/claims/authnmethodsreferences: pwd
                       appid          : 1950a258-227b-4e31-a9cf-717495945fc2
                       appidacr       : 0
                       http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname: Salerno
                       http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname: Daniele
                       ipaddr         : 93.46.197.162
                       name           : Daniele Salerno
                       http://schemas.microsoft.com/identity/claims/objectidentifier: 5d72b67c-ca00-4463-95c9-3ad810bfc3ac
                       puid           : 100320006BC5B715
                       http://schemas.microsoft.com/identity/claims/scope: user_impersonation
                       http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier: pl5QE96BtTForr9DAnfWclsXtrRGcLymUo-0Kx3wAL8
                       http://schemas.microsoft.com/identity/claims/tenantid: 7ca361c3-9161-4ae8-b172-5dfcbd2c5539
                       http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: daniele.salerno@trueverit.com
                       http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn: daniele.salerno@trueverit.com
                       uti            : BwwvpfnoMUO7MydYH-lHAA
                       ver            : 1.0
HttpRequest          : 
                       ClientId        : d5604419-4f9f-4318-8731-186a8a2a8910
                       Method          : POST
                       Url             : 
                       ClientIpAddress : 93.46.197.162
Properties           : 
                       statusCode     : BadRequest
                       serviceRequestId: 
                       statusMessage  : {"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'IotEdgeMlDemoVm-oxwIZ' is not valid according to the validation procedure. The 
                       tracking id is '3ff840d8-b415-470d-bcf2-91ce8d0cd870'. See inner errors for details.","details":[{"code":"QuotaExceeded","message":"The operation couldn't be completed as it 
                       results in exceeding quota limit of Core. Maximum allowed: 4, Current in use: 0, Additional requested: 8. Read more about quota limits at https://aka.ms/AzurePerVMQuotaLimits. 
                       Submit a request for Quota increase using the link https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%22edaac790-1c73-4ad6-99fa-7eb59a597b4b%22,%2
                       2pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D."}]}}
Level                : Error
SubmissionTimestamp  : 07/10/19 09:19:10
EventTimestamp       : 07/10/19 09:17:18
Caller               : daniele.salerno@trueverit.com
Description          : 
Id                   : /subscriptions/edaac790-1c73-4ad6-99fa-7eb59a597b4b/resourcegroups/Gruppo_ML/providers/Microsoft.Resources/deployments/IotEdgeMlDemoVm-oxwIZ/events/5218ceea-833e-45be-8a03-ede7fe
                       21529e/ticks/637060366380272755
EventDataId          : 5218ceea-833e-45be-8a03-ede7fe21529e
CorrelationId        : 3ff840d8-b415-470d-bcf2-91ce8d0cd870
EventName            : Microsoft.Azure.Management.Monitor.Models.LocalizableString
Category             : Microsoft.Azure.Management.Monitor.Models.LocalizableString
ResourceGroupName    : Gruppo_ML
ResourceProviderName : Microsoft.Azure.Management.Monitor.Models.LocalizableString
ResourceId           : /subscriptions/edaac790-1c73-4ad6-99fa-7eb59a597b4b/resourcegroups/Gruppo_ML/providers/Microsoft.Resources/deployments/IotEdgeMlDemoVm-oxwIZ
ResourceType         : 
OperationId          : 3ff840d8-b415-470d-bcf2-91ce8d0cd870
OperationName        : Microsoft.Azure.Management.Monitor.Models.LocalizableString
Status               : Microsoft.Azure.Management.Monitor.Models.LocalizableString
SubStatus            : Microsoft.Azure.Management.Monitor.Models.LocalizableString
SubscriptionId       : edaac790-1c73-4ad6-99fa-7eb59a597b4b
TenantId             : 

Authorization        : 
                       Scope     : /subscriptions/edaac790-1c73-4ad6-99fa-7eb59a597b4b/resourcegroups/Gruppo_ML/providers/Microsoft.Resources/deployments/IotEdgeMlDemoVm-oxwIZ
                       Action    : Microsoft.Resources/deployments/validate/action
                       Role      : 
                       Condition : 
Claims               : 
                       aud            : https://management.core.windows.net/
                       iss            : https://sts.windows.net/7ca361c3-9161-4ae8-b172-5dfcbd2c5539/
                       iat            : 1570439002
                       nbf            : 1570439002
                       exp            : 1570442902
                       http://schemas.microsoft.com/claims/authnclassreference: 1
                       aio            : 42VgYJApV/dRkHojeo37qmLQg1Llvcfmfgx/9UTOQ91zc7/3aiYA
                       http://schemas.microsoft.com/claims/authnmethodsreferences: pwd
                       appid          : 1950a258-227b-4e31-a9cf-717495945fc2
                       appidacr       : 0
                       http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname: Salerno
                       http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname: Daniele
                       ipaddr         : 93.46.197.162
                       name           : Daniele Salerno
                       http://schemas.microsoft.com/identity/claims/objectidentifier: 5d72b67c-ca00-4463-95c9-3ad810bfc3ac
                       puid           : 100320006BC5B715
                       http://schemas.microsoft.com/identity/claims/scope: user_impersonation
                       http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier: pl5QE96BtTForr9DAnfWclsXtrRGcLymUo-0Kx3wAL8
                       http://schemas.microsoft.com/identity/claims/tenantid: 7ca361c3-9161-4ae8-b172-5dfcbd2c5539
                       http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: daniele.salerno@trueverit.com
                       http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn: daniele.salerno@trueverit.com
                       uti            : BwwvpfnoMUO7MydYH-lHAA
                       ver            : 1.0
HttpRequest          : 
                       ClientId        : d5604419-4f9f-4318-8731-186a8a2a8910
                       Method          : POST
                       Url             : 
                       ClientIpAddress : 93.46.197.162
Properties           : 
Level                : Informational
SubmissionTimestamp  : 07/10/19 09:19:10
EventTimestamp       : 07/10/19 09:17:17
Caller               : daniele.salerno@trueverit.com
Description          : 
Id                   : /subscriptions/edaac790-1c73-4ad6-99fa-7eb59a597b4b/resourcegroups/Gruppo_ML/providers/Microsoft.Resources/deployments/IotEdgeMlDemoVm-oxwIZ/events/404fb50f-2257-4fa9-97dd-970335
                       2fee25/ticks/637060366370422335
EventDataId          : 404fb50f-2257-4fa9-97dd-9703352fee25
CorrelationId        : 3ff840d8-b415-470d-bcf2-91ce8d0cd870
EventName            : Microsoft.Azure.Management.Monitor.Models.LocalizableString
Category             : Microsoft.Azure.Management.Monitor.Models.LocalizableString
ResourceGroupName    : Gruppo_ML
ResourceProviderName : Microsoft.Azure.Management.Monitor.Models.LocalizableString
ResourceId           : /subscriptions/edaac790-1c73-4ad6-99fa-7eb59a597b4b/resourcegroups/Gruppo_ML/providers/Microsoft.Resources/deployments/IotEdgeMlDemoVm-oxwIZ
ResourceType         : 
OperationId          : 3ff840d8-b415-470d-bcf2-91ce8d0cd870
OperationName        : Microsoft.Azure.Management.Monitor.Models.LocalizableString
Status               : Microsoft.Azure.Management.Monitor.Models.LocalizableString
SubStatus            : Microsoft.Azure.Management.Monitor.Models.LocalizableString
SubscriptionId       : edaac790-1c73-4ad6-99fa-7eb59a597b4b
TenantId             :

**Comment by drwill-ms** [comment]
> i got the same error of @gearsmotion789. I'm running PowerShell on MacOS.
> @kgremban here is my log:
> 
> statusMessage : {"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'IotEdgeMlDemoVm-oxwIZ' is not valid according to the validation procedure. The
> tracking id is '3ff840d8-b415-470d-bcf2-91ce8d0cd870'. See inner errors for details.","details":[{"code":"QuotaExceeded","message":"The operation couldn't be completed as it
> results in exceeding quota limit of Core. Maximum allowed: 4, Current in use: 0, Additional requested: 8. Read more about quota limits at https://aka.ms/AzurePerVMQuotaLimits.
> Submit a request for Quota increase using the link https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%22edaac790-1c73-4ad6-99fa-7eb59a597b4b%22,%2

@JotunheimOnTb here is the relevant part of your error. The VM we selected has 8 cores, but for your subscription, in that region, for that VM Size family your quota is only 4 cores. You can see what your quota limits are by looking at your subscription in the portal. Click on the "Usage + quotas" menu item, then use the filters to find the relevant restrictions. From there you can 1) ask for a quota increase, 2) identify a different region where you have available quota, or 3) identify a different VM Size family where you have quota and modify the ARM template to use that instead.

I'm sorry. I know quotas can be frustrating.

Regards,
David

**Comment by JotunheimOnTb** [comment]
Thanks u very much, I modified the template and now runs well

**Comment by drwill-ms** [comment]
No reply from @gearsmotion789 since August, and resolved for another report, so closing this for now.
